'use client';

import React, { useState, useEffect, useMemo } from 'react';
import {
  Truck,
  Package,
  Clock,
  MapPin,
  Search,
  Check,
  Copy,
  ChevronRight,
  ChevronDown,
  Mail,
  Leaf,
  ShieldCheck,
  Calendar,
  Sparkles,
  HelpCircle,
  Globe,
  Box,
  BadgeCheck,
  ArrowRight
} from 'lucide-react';

const SECTIONS = [
  { id: 'warehouse', title: 'Where We Ship From', icon: MapPin },
  { id: 'destinations', title: 'Regional Coverage', icon: Globe },
  { id: 'processing', title: 'Processing Timeline', icon: Clock },
  { id: 'delivery', title: 'Transit & Delivery', icon: Truck },
  { id: 'shipping-cost', title: 'Shipping Rates & Thresholds', icon: Box },
  { id: 'tracking', title: 'Order Tracking & Notifications', icon: Package },
  { id: 'delivery-calculator', title: 'Shipping Time Estimator', icon: Calendar },
  { id: 'eco-packaging', title: 'Eco-Packaging Standards', icon: Leaf },
  { id: 'questions', title: 'Support & Inquiries', icon: Mail },
];

const FAQS = [
  {
    q: 'How do I track my order once dispatched?',
    a: 'You will receive an automated email containing your tracking link and carrier details as soon as your package leaves our eco-fulfillment center.',
  },
  {
    q: 'What makes your shipping carbon-neutral?',
    a: 'We calculate the carbon emissions generated by every parcel transit and automatically invest in high-impact reforestation and habitat restoration projects.',
  },
  {
    q: 'Do you offer expedited or overnight shipping?',
    a: 'We offer Express Ground and Carbon-Neutral Expedited options at checkout. Availability depends on your specific shipping zip code.',
  },
  {
    q: 'What if my package is lost or delayed by the carrier?',
    a: 'If your tracking has not updated for over 5 business days, contact our eco-desk at hello@theecoshop.co and we will initiate an inquiry or issue a prompt reshipment.',
  },
  {
    q: 'Do you ship to P.O. Boxes or APO/FPO addresses?',
    a: 'Yes, we ship to all U.S. P.O. Boxes and APO/FPO military addresses using USPS Carbon-Neutral Ground shipping.',
  },
];

const REGIONAL_RATES = [
  { id: 'us-cont', name: 'Contiguous United States', standardCost: 'FREE on orders over $50 ($4.95 flat rate)', expressCost: '$12.95', deliveryDays: '3–5 business days', expressDays: '1–2 business days', freeEligible: true },
  { id: 'us-noncont', name: 'Alaska, Hawaii, & U.S. Territories', standardCost: '$8.95 flat rate', expressCost: '$18.95', deliveryDays: '5–7 business days', expressDays: '2–3 business days', freeEligible: false },
  { id: 'apo-fpo', name: 'APO / FPO Military Addresses', standardCost: 'FREE on orders over $50 ($4.95 flat rate)', expressCost: 'N/A', deliveryDays: '7–12 business days', expressDays: 'N/A', freeEligible: true },
  { id: 'canada', name: 'Canada (Carbon-Offset Intl)', standardCost: '$14.95 flat rate', expressCost: '$24.95', deliveryDays: '6–10 business days', expressDays: '3–4 business days', freeEligible: false },
];

export default function ShippingPolicyClient() {
  const [activeSection, setActiveSection] = useState('warehouse');
  const [searchQuery, setSearchQuery] = useState('');
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const [isCopied, setIsCopied] = useState(false);

  // Estimator State
  const [selectedRegion, setSelectedRegion] = useState('us-cont');
  const [cartAmount, setCartAmount] = useState<number>(65);

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setActiveSection(entry.target.id);
          }
        });
      },
      {
        rootMargin: '-15% 0px -60% 0px',
        threshold: 0,
      }
    );

    SECTIONS.forEach((section) => {
      const el = document.getElementById(section.id);
      if (el) observer.observe(el);
    });

    return () => observer.disconnect();
  }, []);

  const handleCopyEmail = () => {
    navigator.clipboard.writeText('hello@theecoshop.co');
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2200);
  };

  const scrollToSection = (id: string) => {
    const element = document.getElementById(id);
    if (element) {
      const yOffset = -90;
      const y = element.getBoundingClientRect().top + window.pageYOffset + yOffset;
      window.scrollTo({ top: y, behavior: 'smooth' });
    }
  };

  const currentRegionInfo = useMemo(() => {
    return REGIONAL_RATES.find((r) => r.id === selectedRegion) || REGIONAL_RATES[0];
  }, [selectedRegion]);

  return (
    <div className="min-h-screen bg-[#F7F6F0] text-[#1B3D2F] font-sans selection:bg-[#4A7C59]/20 selection:text-[#1B3D2F]">
      
      {}
      <header className="relative border-b border-[#E5E2D8] bg-gradient-to-b from-[#EEECE2] via-[#F7F6F0] to-[#F7F6F0] px-6 pt-16 pb-12 sm:pt-20 sm:pb-16">
        <div className="mx-auto max-w-4xl text-center">
          
          <div className="inline-flex items-center gap-2 rounded-full border border-[#4A7C59]/20 bg-[#4A7C59]/10 px-4 py-1.5 text-xs font-semibold uppercase tracking-widest text-[#1B3D2F]">
            <Truck className="h-3.5 w-3.5 text-[#4A7C59]" />
            Official Store Policy
          </div>

          <h1 className="mt-4 font-serif text-3xl font-bold tracking-tight text-[#1B3D2F] sm:text-5xl">
            Shipping Policy
          </h1>

          <p className="mt-3 text-center font-sans text-xs sm:text-sm text-[#4A7C59] font-medium">
            Last updated: September 25, 2026
          </p>

          <p className="mt-4 max-w-xl mx-auto text-sm sm:text-base text-[#3A4A40] leading-relaxed">
            Transparent, sustainable, and 100% carbon-neutral dispatch from our eco-warehouse directly to your doorstep.
          </p>

          {/* Quick Search Bar */}
          <div className="mt-8 mx-auto w-full max-w-md">
            <div className="relative">
              <Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-[#4A7C59]" />
              <input
                type="text"
                placeholder="Search shipping policy (e.g., tracking, rates, timeline)..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full rounded-2xl border border-[#D5CEC3] bg-white/90 py-3 pl-10 pr-4 text-sm text-[#1B3D2F] shadow-sm backdrop-blur transition focus:border-[#1B3D2F] focus:bg-white focus:outline-none focus:ring-2 focus:ring-[#1B3D2F]/10"
              />
            </div>
          </div>

          {/* TRUST STATS HEADER CARDS */}
          <div className="mt-10 grid gap-4 sm:grid-cols-3">
            <div className="rounded-2xl border border-[#E5E2D8] bg-white p-4 shadow-sm transition hover:shadow-md">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#EEECE2] text-[#1B3D2F]">
                  <Globe className="h-5 w-5 text-[#4A7C59]" />
                </div>
                <div className="text-left">
                  <h3 className="font-serif text-sm font-semibold text-[#1B3D2F]">100% Carbon Neutral</h3>
                  <p className="text-xs text-[#5C6E63]">Offsetting all transit emissions.</p>
                </div>
              </div>
            </div>

            <div className="rounded-2xl border border-[#E5E2D8] bg-white p-4 shadow-sm transition hover:shadow-md">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#EEECE2] text-[#1B3D2F]">
                  <Leaf className="h-5 w-5 text-[#4A7C59]" />
                </div>
                <div className="text-left">
                  <h3 className="font-serif text-sm font-semibold text-[#1B3D2F]">Plastic-Free Mailers</h3>
                  <p className="text-xs text-[#5C6E63]">100% compostable boxes &amp; tape.</p>
                </div>
              </div>
            </div>

            <div className="rounded-2xl border border-[#E5E2D8] bg-white p-4 shadow-sm transition hover:shadow-md">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#EEECE2] text-[#1B3D2F]">
                  <ShieldCheck className="h-5 w-5 text-[#4A7C59]" />
                </div>
                <div className="text-left">
                  <h3 className="font-serif text-sm font-semibold text-[#1B3D2F]">Real-Time Tracking</h3>
                  <p className="text-xs text-[#5C6E63]">Instant dispatch alerts via email.</p>
                </div>
              </div>
            </div>
          </div>

        </div>
      </header>

      {}
      <div className="mx-auto max-w-6xl px-6 py-12 lg:py-16">
        <div className="grid grid-cols-1 gap-12 lg:grid-cols-12">
          
          {/* SIDEBAR NAVIGATION (STICKY WITH SCROLLSPY) */}
          <aside className="lg:col-span-4">
            <div className="sticky top-8 space-y-6">
              
              <div className="rounded-2xl border border-[#E5E2D8] bg-white p-5 shadow-sm">
                <h2 className="mb-4 font-serif text-xs font-bold uppercase tracking-wider text-[#1B3D2F]">
                  Policy Table of Contents
                </h2>
                <nav className="space-y-1">
                  {SECTIONS.map((section) => {
                    const Icon = section.icon;
                    const isActive = activeSection === section.id;
                    const isMatchedSearch = searchQuery && section.title.toLowerCase().includes(searchQuery.toLowerCase());

                    return (
                      <button
                        key={section.id}
                        onClick={() => scrollToSection(section.id)}
                        className={`group flex w-full items-center justify-between rounded-xl px-3.5 py-2.5 text-left text-xs font-medium transition ${
                          isActive
                            ? 'bg-[#1B3D2F] text-white shadow-sm'
                            : isMatchedSearch
                            ? 'bg-[#EEECE2] text-[#1B3D2F] font-bold'
                            : 'text-[#5C6E63] hover:bg-[#F7F6F0] hover:text-[#1B3D2F]'
                        }`}
                      >
                        <span className="flex items-center gap-2.5">
                          <Icon className={`h-4 w-4 ${isActive ? 'text-white' : 'text-[#4A7C59] group-hover:text-[#1B3D2F]'}`} />
                          {section.title}
                        </span>
                        <ChevronRight className={`h-3.5 w-3.5 transition-transform ${isActive ? 'translate-x-0.5 text-white' : 'opacity-0 group-hover:opacity-100 text-[#5C6E63]'}`} />
                      </button>
                    );
                  })}
                </nav>
              </div>

              {/* DIRECT SUPPORT CARD */}
              <div className="rounded-2xl border border-[#D5CEC3] bg-gradient-to-br from-[#EEECE2] via-[#F7F6F0] to-[#F7F6F0] p-5 shadow-sm">
                <div className="flex items-center gap-2 text-[#1B3D2F]">
                  <Mail className="h-5 w-5 text-[#4A7C59]" />
                  <h3 className="font-serif text-sm font-semibold">
                    Need Shipping Support?
                  </h3>
                </div>
                <p className="mt-2 text-xs leading-relaxed text-[#5C6E63]">
                  Have a question about a placed order or special handling? Email our care team.
                </p>
                <button
                  onClick={handleCopyEmail}
                  className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-[#1B3D2F] py-2.5 px-4 text-xs font-semibold text-white transition hover:bg-[#2A5240] active:scale-[0.99]"
                >
                  {isCopied ? <Check className="h-3.5 w-3.5 text-[#A2C4AB]" /> : <Copy className="h-3.5 w-3.5" />}
                  {isCopied ? 'Email Address Copied!' : 'hello@theecoshop.co'}
                </button>
              </div>

            </div>
          </aside>

          {}
          <main className="space-y-8 lg:col-span-8">
            
            {/* SECTION 1: WHERE WE SHIP FROM */}
            <section id="warehouse" className="scroll-mt-28 rounded-2xl border border-[#E5E2D8] bg-white p-6 shadow-sm transition sm:p-8">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#EEECE2] text-[#1B3D2F]">
                  <MapPin className="h-5 w-5 text-[#4A7C59]" />
                </div>
                <h2 className="font-serif text-2xl font-semibold text-[#1B3D2F]">
                  Where We Ship From
                </h2>
              </div>

              <div className="mt-4 text-sm leading-relaxed text-[#3A4A40] space-y-3">
                <p>
                  All orders ship directly from our primary eco-fulfillment center in{' '}
                  <span className="font-semibold text-[#1B3D2F]">Portland, Oregon (United States)</span>.
                </p>
                <p className="text-xs text-[#5C6E63]">
                  Our facility is 100% solar-powered and operates under strict zero-waste packing protocols to ensure minimal ecological footprint prior to carrier dispatch.
                </p>
              </div>
            </section>

            {/* SECTION 2: REGIONAL COVERAGE */}
            <section id="destinations" className="scroll-mt-28 rounded-2xl border border-[#E5E2D8] bg-white p-6 shadow-sm transition sm:p-8">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#EEECE2] text-[#1B3D2F]">
                  <Globe className="h-5 w-5 text-[#4A7C59]" />
                </div>
                <h2 className="font-serif text-2xl font-semibold text-[#1B3D2F]">
                  Regional Coverage
                </h2>
              </div>

              <div className="mt-4 text-sm leading-relaxed text-[#3A4A40] space-y-3">
                <p>
                  We currently ship to addresses across <span className="font-semibold text-[#1B3D2F]">all 50 U.S. states, U.S. Territories, APO/FPO military addresses, and Canada</span>.
                </p>
                <p className="text-xs text-[#5C6E63]">
                  Looking for additional international destinations? We are actively testing carbon-offset ocean transit partners to expand our reach responsibly. Join our newsletter to get notified when new regions open up.
                </p>
              </div>
            </section>

            {/* SECTION 3: PROCESSING TIME */}
            <section id="processing" className="scroll-mt-28 rounded-2xl border border-[#E5E2D8] bg-white p-6 shadow-sm transition sm:p-8">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#EEECE2] text-[#1B3D2F]">
                  <Clock className="h-5 w-5 text-[#4A7C59]" />
                </div>
                <h2 className="font-serif text-2xl font-semibold text-[#1B3D2F]">
                  Processing Timeline
                </h2>
              </div>

              <div className="mt-4 text-sm leading-relaxed text-[#3A4A40] space-y-3">
                <p>
                  Orders are processed and handed to our carbon-neutral postal partners within{' '}
                  <span className="font-semibold text-[#1B3D2F]">1–2 business days</span> of purchase.
                </p>
                <p className="text-xs text-[#5C6E63]">
                  Please note that orders placed on weekends or official postal holidays are queued for fulfillment on the following business day.
                </p>
              </div>
            </section>

            {/* SECTION 4: TRANSIT & DELIVERY */}
            <section id="delivery" className="scroll-mt-28 rounded-2xl border border-[#E5E2D8] bg-white p-6 shadow-sm transition sm:p-8">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#EEECE2] text-[#1B3D2F]">
                  <Truck className="h-5 w-5 text-[#4A7C59]" />
                </div>
                <h2 className="font-serif text-2xl font-semibold text-[#1B3D2F]">
                  Transit &amp; Delivery Estimates
                </h2>
              </div>

              <div className="mt-4 text-sm leading-relaxed text-[#3A4A40] space-y-3">
                <p>
                  Once dispatched, standard orders typically arrive within{' '}
                  <span className="font-semibold text-[#1B3D2F]">3–5 business days</span>, depending on your location.
                </p>
                <p className="text-xs text-[#5C6E63]">
                  Severe weather events or seasonal carrier surges may occasionally extend transit times. You can always view updated tracking steps in your dispatch notification.
                </p>
              </div>
            </section>

            {/* SECTION 5: SHIPPING RATES */}
            <section id="shipping-cost" className="scroll-mt-28 rounded-2xl border border-[#E5E2D8] bg-white p-6 shadow-sm transition sm:p-8">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#EEECE2] text-[#1B3D2F]">
                  <Box className="h-5 w-5 text-[#4A7C59]" />
                </div>
                <h2 className="font-serif text-2xl font-semibold text-[#1B3D2F]">
                  Shipping Rates &amp; Free Shipping Thresholds
                </h2>
              </div>

              <div className="mt-4 text-sm leading-relaxed text-[#3A4A40] space-y-3">
                <p>
                  We offer <span className="font-semibold text-[#1B3D2F]">Free Standard Shipping on all U.S. orders over $50</span>. For orders under $50, a standard flat rate of <span className="font-semibold text-[#1B3D2F]">$4.95</span> applies.
                </p>
                <p>
                  Any calculated shipping cost is explicitly displayed before you enter payment details at checkout — never as a hidden charge afterwards.
                </p>
              </div>

              <div className="mt-4 rounded-xl border border-[#E5E2D8] bg-[#F7F6F0] p-4 text-xs text-[#5C6E63]">
                💡 <strong>Fair Pricing Pledge:</strong> We do not mark up shipping rates for profit. What you pay directly reflects the exact cost required to deliver your package cleanly and sustainably.
              </div>
            </section>

            {/* SECTION 6: ORDER TRACKING */}
            <section id="tracking" className="scroll-mt-28 rounded-2xl border border-[#E5E2D8] bg-white p-6 shadow-sm transition sm:p-8">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#EEECE2] text-[#1B3D2F]">
                  <Package className="h-5 w-5 text-[#4A7C59]" />
                </div>
                <h2 className="font-serif text-2xl font-semibold text-[#1B3D2F]">
                  Order Tracking &amp; Notifications
                </h2>
              </div>

              <div className="mt-4 text-sm leading-relaxed text-[#3A4A40] space-y-3">
                <p>
                  You will receive an instant order confirmation email immediately upon checkout, followed by a separate notification containing live carrier tracking information once your package is scanned by the driver.
                </p>
                <p className="text-xs text-[#5C6E63]">
                  Tracking updates usually appear within 24 hours of package handoff.
                </p>
              </div>
            </section>

            {}
            <section id="delivery-calculator" className="scroll-mt-28 rounded-2xl border border-[#2A5240]/30 bg-gradient-to-br from-[#1B3D2F] to-[#2A5240] p-6 text-white shadow-md sm:p-8">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-white/10 text-[#A2C4AB]">
                  <Calendar className="h-5 w-5" />
                </div>
                <div>
                  <h2 className="font-serif text-2xl font-semibold">
                    Interactive Shipping Estimator
                  </h2>
                  <p className="text-xs text-[#C5D8C9]">
                    Select your destination to estimate transit times and free shipping eligibility
                  </p>
                </div>
              </div>

              <div className="mt-6 grid gap-4 sm:grid-cols-2">
                <div>
                  <label className="block text-xs font-semibold text-[#A2C4AB] mb-1.5">
                    Shipping Destination Region
                  </label>
                  <select
                    value={selectedRegion}
                    onChange={(e) => setSelectedRegion(e.target.value)}
                    className="w-full rounded-xl bg-[#0F2218] border border-[#3A5C4A] px-3.5 py-2.5 text-xs text-white focus:outline-none focus:border-[#A2C4AB]"
                  >
                    {REGIONAL_RATES.map((region) => (
                      <option key={region.id} value={region.id}>
                        {region.name}
                      </option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-xs font-semibold text-[#A2C4AB] mb-1.5">
                    Estimated Cart Total ($)
                  </label>
                  <input
                    type="number"
                    value={cartAmount}
                    onChange={(e) => setCartAmount(Number(e.target.value))}
                    className="w-full rounded-xl bg-[#0F2218] border border-[#3A5C4A] px-3.5 py-2.5 text-xs text-white focus:outline-none focus:border-[#A2C4AB]"
                    placeholder="Enter order value"
                  />
                </div>
              </div>

              {/* Estimator Dynamic Results */}
              <div className="mt-6 rounded-xl bg-[#0F2218]/90 border border-[#3A5C4A] p-4 grid gap-4 sm:grid-cols-3">
                <div>
                  <span className="text-[11px] uppercase tracking-wider text-[#A2C4AB] block">Est. Transit Time:</span>
                  <span className="font-serif text-sm font-bold text-white mt-1 block">
                    {currentRegionInfo.deliveryDays}
                  </span>
                </div>

                <div>
                  <span className="text-[11px] uppercase tracking-wider text-[#A2C4AB] block">Standard Rate:</span>
                  <span className="font-serif text-sm font-bold text-white mt-1 block">
                    {currentRegionInfo.freeEligible && cartAmount >= 50 ? (
                      <span className="text-[#A2C4AB]">FREE (Order &gt; $50)</span>
                    ) : (
                      currentRegionInfo.standardCost
                    )}
                  </span>
                </div>

                <div>
                  <span className="text-[11px] uppercase tracking-wider text-[#A2C4AB] block">Express Rate:</span>
                  <span className="font-serif text-sm font-bold text-white mt-1 block">
                    {currentRegionInfo.expressCost} ({currentRegionInfo.expressDays})
                  </span>
                </div>
              </div>
            </section>

            {/* SECTION 8: ECO-PACKAGING */}
            <section id="eco-packaging" className="scroll-mt-28 rounded-2xl border border-[#E5E2D8] bg-[#EEECE2]/60 p-6 shadow-sm sm:p-8">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-white text-[#1B3D2F]">
                  <Leaf className="h-5 w-5 text-[#4A7C59]" />
                </div>
                <div>
                  <h2 className="font-serif text-2xl font-semibold text-[#1B3D2F]">
                    Eco-Packaging Standards
                  </h2>
                  <p className="text-xs text-[#5C6E63]">Zero single-use plastics from tape to mailing box</p>
                </div>
              </div>

              <div className="mt-6 grid gap-4 sm:grid-cols-3 text-xs">
                <div className="rounded-xl border border-[#E5E2D8] bg-white p-3.5">
                  <strong className="text-[#1B3D2F] block font-serif mb-1">Cornstarch Peanuts</strong>
                  100% biodegradable and dissolves safely in warm water in under 60 seconds.
                </div>
                <div className="rounded-xl border border-[#E5E2D8] bg-white p-3.5">
                  <strong className="text-[#1B3D2F] block font-serif mb-1">Water-Activated Tape</strong>
                  Reinforced kraft paper tape that can be recycled directly along with your box.
                </div>
                <div className="rounded-xl border border-[#E5E2D8] bg-white p-3.5">
                  <strong className="text-[#1B3D2F] block font-serif mb-1">Soy-Based Inks</strong>
                  All box graphics and shipping labels are printed using non-toxic soy inks.
                </div>
              </div>
            </section>

            {/* SECTION 9: ACCORDION FAQ */}
            <section className="rounded-2xl border border-[#E5E2D8] bg-white p-6 shadow-sm sm:p-8">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#EEECE2] text-[#1B3D2F]">
                  <HelpCircle className="h-5 w-5 text-[#4A7C59]" />
                </div>
                <h2 className="font-serif text-2xl font-semibold text-[#1B3D2F]">
                  Frequently Asked Questions
                </h2>
              </div>

              <div className="mt-6 divide-y divide-[#E5E2D8]">
                {FAQS.map((faq, index) => (
                  <div key={index} className="py-4 first:pt-0 last:pb-0">
                    <button
                      onClick={() => setOpenFaq(openFaq === index ? null : index)}
                      className="flex w-full items-center justify-between text-left text-sm font-semibold text-[#1B3D2F] hover:text-[#4A7C59]"
                    >
                      <span>{faq.q}</span>
                      <ChevronDown className={`h-4 w-4 shrink-0 text-[#5C6E63] transition-transform ${openFaq === index ? 'rotate-180 text-[#1B3D2F]' : ''}`} />
                    </button>
                    {openFaq === index && (
                      <p className="mt-2.5 text-xs leading-relaxed text-[#5C6E63]">
                        {faq.a}
                      </p>
                    )}
                  </div>
                ))}
              </div>
            </section>

            {/* SECTION 10: SUPPORT CARD */}
            <section id="questions" className="scroll-mt-28 rounded-2xl bg-[#1B3D2F] p-8 text-white shadow-md">
              <div className="flex items-center gap-3">
                <Sparkles className="h-6 w-6 text-[#A2C4AB]" />
                <h2 className="font-serif text-2xl font-semibold">
                  Still Have Questions?
                </h2>
              </div>

              <p className="mt-3 text-sm text-[#C5D8C9] leading-relaxed max-w-xl">
                Email us at{' '}
                <a
                  href="mailto:hello@theecoshop.co"
                  className="font-semibold text-white underline hover:text-[#A2C4AB] transition"
                >
                  hello@theecoshop.co
                </a>{' '}
                and our customer care desk will help track down your order or answer custom freight questions.
              </p>

              <div className="mt-6 flex flex-wrap items-center gap-4">
                <button
                  onClick={handleCopyEmail}
                  className="inline-flex items-center gap-2 rounded-xl bg-[#2A5240] px-5 py-3 text-xs font-semibold text-white transition hover:bg-[#3A6B53] active:scale-[0.98] border border-[#4A7C59]/40"
                >
                  <Mail className="h-4 w-4 text-[#A2C4AB]" />
                  {isCopied ? 'Email Copied to Clipboard!' : 'hello@theecoshop.co'}
                </button>

                <a
                  href="https://theecoshop.co"
                  className="inline-flex items-center gap-1.5 text-xs font-medium text-[#C5D8C9] hover:text-white transition"
                >
                  Return to Storefront
                  <ArrowRight className="h-4 w-4" />
                </a>
              </div>
            </section>

          </main>
        </div>
      </div>

    </div>
  );
}